In [1]:
import os
os.chdir("/Users/mac/Desktop/Dinger")

In [2]:
from Dinger.controller import Controller

In [3]:
controller = Controller()

### (1) Main 함수로 controller 사용하기

In [ ]:
controller.main()

### (2) Method 하나씩 돌려보기

### get_standard_df

In [4]:
controller.get_standard_df()

한국 시장의 기준값 데이터 프레임을 조회합니다.

,BPS,PER,PBR,EPS,DIV,DPS,매출액,영업이익,당기순이익,ROA,ROE,베타,MKT_VAL
SEC_NM_KOR,,,,,,,,,,,,,
IT,12561.88,26.01,1.89,1116.41,0.89,148.30,2965.95,399.54,304.36,2.79,4.01,1.01,764310.56
건강관리,10434.95,26.25,3.42,814.03,0.64,124.79,540.08,51.22,46.90,-1.27,-1461.58,0.96,347073.89
경기관련소비재,23448.37,17.90,1.31,2505.02,1.60,438.85,4310.53,272.28,258.61,1.63,1.94,0.88,346574.47
금융,31795.46,6.74,0.69,3783.89,4.46,823.24,25541.65,1591.06,1250.60,1.77,9.18,0.76,1104869.20
산업재,20988.79,34.75,1.43,1636.03,1.67,333.29,5517.67,424.33,313.91,3.06,2.78,0.90,349453.52
소재,64600.90,14.44,1.29,6795.96,1.84,800.91,4535.81,378.23,306.29,6.45,10.68,0.87,421471.27
에너지,36247.31,22.77,1.59,3023.58,1.62,1140.78,16907.61,1985.81,1290.97,1.54,2.76,0.78,580795.64
유틸리티,106087.00,32.45,1.14,5693.65,2.90,1307.35,18977.24,-3598.53,-2754.82,3.25,5.85,0.39,624011.76
커뮤니케이션서비스,16708.39,23.93,1.96,2776.34,0.83,269.54,2445.65,230.65,133.89,0.43,-1.00,0.93,772715.33
필수소비재,60567.13,12.23,1.24,4289.28,1.78,719.17,3866.59,260.45,183.34,2.52,4.08,0.73,274516.05

In [8]:
controller.get_standard_df()

미국 시장의 기준값 데이터 프레임을 저장합니다.

In [6]:
controller.get_standard_df()

한국 시장의 기준값 데이터 프레임을 저장합니다.

In [7]:
controller.get_standard_df()

미국 시장의 기준값 데이터 프레임을 저장합니다.

### get_score_df

In [8]:
controller.get_score_df()

한국 시장의 스코어 데이터 프레임을 조회합니다.

,CMP_KOR,SEC_NM_KOR,BPS,PER,PBR,EPS,DIV,DPS,매출액,영업이익,당기순이익,ROA,ROE,베타,MKT_VAL,Score
종목코드,,,,,,,,,,,,,,,,
005380,현대차,경기관련소비재,289609.00,9.33,0.61,18979.00,2.82,5000.00,359999.00,29798.00,30848.00,4.00,11.30,1.40,24960718.00,12.00
000270,기아,경기관련소비재,87073.00,5.99,0.82,11874.00,4.22,3000.00,218760.00,22341.00,18810.00,8.40,16.00,1.44,17869227.00,12.00
012330,현대모비스,경기관련소비재,387397.00,7.90,0.52,25645.00,1.98,4000.00,123081.00,4033.00,7697.00,4.90,7.10,1.49,12831205.00,12.00
051900,LG생활건강,경기관련소비재,321556.00,12.64,1.98,50395.00,1.88,12000.00,18627.00,2166.00,1260.00,6.40,8.60,0.79,5969275.00,12.00
090430,아모레퍼시픽,경기관련소비재,69049.00,36.88,1.51,2820.00,0.94,980.00,9457.00,-195.00,-372.00,2.80,3.60,0.84,3163288.00,8.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
070590,한솔인티큐브,IT,1931.00,67.92,0.84,24.00,0.00,0.00,163.00,-6.00,-5.00,-7.90,-8.70,1.00,13348.00,2.00
372800,아이티아이즈,IT,5035.00,0.00,1.61,0.00,0.00,0.00,119.00,-30.00,-12.00,0.70,1.00,1.99,13056.00,2.00
033200,모아텍,IT,7713.00,0.00,0.80,0.00,0.00,0.00,81.00,-6.00,-4.00,-2.10,-2.40,1.67,11439.00,2.00
032960,동일기연,IT,17895.00,4.65,0.60,2312.00,0.37,40.00,76.00,2.00,5.00,6.30,6.80,1.12,9769.00,6.00
321260,프로이천,IT,1005.00,0.00,2.10,0.00,0.95,20.00,132.00,20.00,26.00,21.50,25.40,0.61,8923.00,5.00

In [9]:
controller.get_score_df()

미국 시장의 스코어 데이터 프레임을 조회합니다.

,Symbol,Name,Sector,Industry,Sales,Revenue,MarCap,PER,PBR,ROA,...,Price,Beta,DIVIDEND,Sales_score,Revenue_score,MarCap_score,ROA_score,ROE_score,PER_score,total_score
0,MMM,3M,Industrials,Industrial Conglomerates,35090000000.00,4150000000.00,68570000000.00,17.38,5.16,8.90,...,122.83,0.99,4.80,1.00,1.00,1.00,0.00,1.00,1.00,5.00
1,AOS,A. O. Smith,Industrials,Building Products,3850000000.00,517200000.00,8760000000.00,17.27,4.88,15.30,...,55.01,1.19,1.99,0.00,0.00,0.00,1.00,1.00,1.00,3.00
2,ABT,Abbott,Health Care,Health Care Equipment,45550000000.00,8550000000.00,188760000000.00,22.71,5.25,11.50,...,106.36,0.71,1.72,1.00,1.00,1.00,1.00,0.00,1.00,5.00
3,ABBV,AbbVie,Health Care,Pharmaceuticals,57350000000.00,12570000000.00,249890000000.00,20.12,17.18,8.60,...,141.21,0.68,3.97,1.00,1.00,1.00,0.00,1.00,1.00,5.00
4,ABMD,Abiomed,Health Care,Health Care Equipment,1060000000.00,217600000.00,12390000000.00,58.92,8.28,13.40,...,266.36,1.37,NaN,0.00,0.00,0.00,1.00,0.00,0.00,1.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
498,YUM,Yum! Brands,Consumer Discretionary,Restaurants,6680000000.00,1480000000.00,33440000000.00,23.48,NaN,24.70,...,114.42,1.03,1.94,0.00,0.00,0.00,1.00,0.00,1.00,2.00
499,ZBRA,Zebra Technologies,Information Technology,Electronic Equipment & Instruments,5800000000.00,497000000.00,15000000000.00,31.92,6.09,7.80,...,293.50,1.67,NaN,0.00,0.00,0.00,0.00,0.00,1.00,1.00
500,ZBH,Zimmer Biomet,Health Care,Health Care Equipment,7410000000.00,299600000.00,24210000000.00,83.93,2.06,1.00,...,116.83,1.15,0.80,0.00,0.00,0.00,0.00,0.00,0.00,0.00
501,ZION,Zions Bancorporation,Financials,Regional Banks,2300000000.00,824000000.00,8630000000.00,10.73,1.66,0.90,...,57.30,1.23,2.86,0.00,0.00,0.00,0.00,0.00,1.00,1.00
502,ZTS,Zoetis,Health Care,Pharmaceuticals,8000000000.00,2090000000.00,75120000000.00,37.76,17.08,15.10,...,162.16,0.76,0.78,0.00,0.00,0.00,1.00,1.00,0.00,2.00

In [10]:
controller.get_score_df()

한국 시장의 스코어 데이터 프레임을 저장합니다.

In [4]:
controller.get_score_df()

미국 시장의 스코어 데이터 프레임을 저장합니다.

### get_top_n_sectors_df

In [4]:
controller.get_top_n_sectors_df()

한국 시장의 상위 섹터 데이터 프레임을 조회합니다.

,BPS,PER,PBR,EPS,DIV,DPS,매출액,영업이익,당기순이익,ROA,ROE,베타,MKT_VAL,Score
SEC_NM_KOR,,,,,,,,,,,,,,
유틸리티,106087.00,32.45,1.14,5693.65,2.90,1307.35,18977.24,-3598.53,-2754.82,3.25,5.85,0.39,624011.76,7.06
건강관리,10434.95,26.25,3.42,814.03,0.64,124.79,540.08,51.22,46.90,-1.27,-1461.58,0.96,347073.89,5.54
필수소비재,60567.13,12.23,1.24,4289.28,1.78,719.17,3866.59,260.45,183.34,2.52,4.08,0.73,274516.05,5.15

In [6]:
controller.get_top_n_sectors_df()

미국 시장의 상위 섹터 데이터 프레임을 조회합니다.

,Sales,Revenue,MarCap,PER,PBR,ROA,ROE,Volume,Price,Beta,DIVIDEND,Sales_score,Revenue_score,MarCap_score,ROA_score,ROE_score,PER_score,total_score
Sector,,,,,,,,,,,,,,,,,,
Information Technology,1692280000000.00,382109500000.00,9345480000000.00,4116.26,816.42,908.30,1788.40,456585087.00,13532.74,89.69,84.63,18.00,16.00,14.00,29.00,39.00,61.00,177.00
Industrials,1454580000000.00,139600200000.00,2797520000000.00,1657.23,374.47,629.90,1412.30,84586644.00,11227.02,79.24,99.59,21.00,22.00,23.00,31.00,41.00,38.00,176.00
Consumer Discretionary,1965600000000.00,166098500000.00,4394990000000.00,1437.25,1620.89,514.60,79.00,240235191.00,16740.91,78.83,82.07,11.00,17.00,9.00,27.00,44.00,39.00,147.00

In [9]:
controller.get_top_n_sectors_df()

한국 시장의 상위 섹터 데이터 프레임을 저장합니다.

In [10]:
controller.get_top_n_sectors_df()

미국 시장의 상위 섹터 데이터 프레임을 저장합니다.

### get_universe_df

In [9]:
controller.get_universe_df()

===입력 가능 섹터 리스트===
['경기관련소비재', '건강관리', '커뮤니케이션서비스', '금융', '에너지', '산업재', '유틸리티', '필수소비재', '소재', 'IT']
한국 시장의 유니버스 데이터 프레임을 조회합니다.

,CMP_KOR,SEC_NM_KOR,BPS,PER,PBR,EPS,DIV,DPS,매출액,영업이익,당기순이익,ROA,ROE,베타,MKT_VAL,Score
종목코드,,,,,,,,,,,,,,,,
137310,에스디바이오센서,건강관리,21658.00,2.51,1.27,10918.00,4.61,1266.00,7950.00,3481.00,3386.00,48.60,63.70,0.13,992180.00,14.00
145720,덴티움,건강관리,33841.00,13.55,2.58,6434.00,0.29,250.00,967.00,352.00,362.00,17.30,32.50,0.88,530861.00,13.00
096530,씨젠,건강관리,20971.00,2.65,1.31,10359.00,3.65,1000.00,1284.00,130.00,251.00,25.50,33.50,1.16,944455.00,13.00
100120,뷰웍스,건강관리,20479.00,9.69,1.69,3575.00,2.16,750.00,637.00,160.00,78.00,12.40,16.00,0.77,242595.00,13.00
000640,동아쏘시오홀딩스,건강관리,154410.00,10.23,0.65,9768.00,1.50,1500.00,2610.00,142.00,89.00,0.50,1.10,0.56,342498.00,13.00
005830,DB손해보험,금융,110605.00,3.83,0.50,14482.00,6.31,3500.00,59734.00,3908.00,2983.00,1.80,19.10,0.55,2593404.00,14.00
055550,신한지주,금융,88548.00,4.78,0.39,7308.00,5.62,1960.00,75869.00,17492.00,13399.00,0.80,11.50,0.73,14679149.00,13.00
105560,KB금융,금융,121808.00,4.18,0.38,11134.00,6.32,2940.00,257208.00,16002.00,13080.00,0.80,11.70,0.74,14640560.00,13.00
001450,현대해상,금융,63866.00,5.67,0.47,5286.00,4.94,1480.00,53586.00,2903.00,2140.00,1.40,15.70,0.42,1793945.00,13.00
016360,삼성증권,금융,68096.00,2.89,0.46,10810.00,12.16,3800.00,40026.00,1828.00,1368.00,0.90,9.50,0.93,1897625.00,12.00
001120,LX인터내셔널,산업재,49349.00,4.29,0.85,9733.00,5.51,2300.00,50200.00,2894.00,2309.00,12.60,32.10,0.71,1181308.00,14.00
012750,에스원,산업재,42676.00,15.33,1.37,3815.00,4.27,2500.00,6255.00,533.00,391.00,8.20,11.30,0.55,1400460.00,14.00
010780,아이에스동서,산업재,40644.00,8.78,0.74,3447.00,3.97,1200.00,5752.00,823.00,550.00,7.80,20.30,0.86,420526.00,14.00
003550,LG,산업재,132574.00,4.84,0.57,15504.00,3.73,2800.00,17381.00,5005.00,4780.00,13.40,15.20,1.16,6261051.00,13.00
241560,두산밥캣,산업재,43105.00,7.59,0.68,3845.00,4.11,1200.00,21803.00,3050.00,1383.00,5.40,10.70,1.19,1434365.00,13.00

In [10]:
controller.get_universe_df()

===입력 가능 섹터 리스트===
['Industrials', 'Health Care', 'Information Technology', 'Communication Services', 'Consumer Staples', 'Consumer Discretionary', 'Utilities', 'Financials', 'Materials', 'Real Estate', 'Energy']
존재하지 않는 섹터입니다.
미국 시장의 유니버스 데이터 프레임을 조회합니다.

,Symbol,Name,Sector,Industry,Sales,Revenue,MarCap,PER,PBR,ROA,...,Beta,DIVIDEND,Sales_score,Revenue_score,MarCap_score,ROA_score,ROE_score,PER_score,total_score,cnn_score
104,CVX,Chevron Corporation,Energy,Integrated Oil & Gas,206100000000.00,29050000000.00,310090000000.00,10.86,2.06,11.80,...,1.14,3.50,1.00,1.00,1.00,1.00,1.00,1.00,6.00,NaN
124,COP,ConocoPhillips,Energy,Oil & Gas Exploration & Production,65370000000.00,15910000000.00,140880000000.00,9.42,2.94,17.40,...,1.31,3.88,1.00,1.00,1.00,1.00,1.00,1.00,6.00,NaN
190,XOM,ExxonMobil,Energy,Integrated Oil & Gas,352200000000.00,38900000000.00,400100000000.00,10.68,2.33,11.10,...,1.06,3.61,1.00,1.00,1.00,0.00,1.00,1.00,5.00,NaN
295,MPC,Marathon Petroleum,Energy,Oil & Gas Refining & Marketing,160800000000.00,8180000000.00,49060000000.00,6.75,2.02,9.00,...,1.69,2.32,1.00,1.00,0.00,0.00,1.00,1.00,4.00,NaN
466,VLO,Valero Energy,Energy,Oil & Gas Refining & Marketing,155610000000.00,7060000000.00,44460000000.00,6.55,2.20,11.90,...,1.67,3.43,1.00,0.00,0.00,1.00,1.00,1.00,4.00,NaN
2,ABT,Abbott,Health Care,Health Care Equipment,45550000000.00,8550000000.00,188760000000.00,22.71,5.25,11.50,...,0.71,1.72,1.00,1.00,1.00,1.00,0.00,1.00,5.00,NaN
3,ABBV,AbbVie,Health Care,Pharmaceuticals,57350000000.00,12570000000.00,249890000000.00,20.12,17.18,8.60,...,0.68,3.97,1.00,1.00,1.00,0.00,1.00,1.00,5.00,NaN
39,AMGN,Amgen,Health Care,Biotechnology,26380000000.00,6580000000.00,125960000000.00,20.13,52.57,10.80,...,0.56,3.27,0.00,1.00,1.00,1.00,1.00,1.00,5.00,NaN
307,MRK,Merck & Co.,Health Care,Pharmaceuticals,57170000000.00,16640000000.00,223540000000.00,13.44,5.16,16.10,...,0.34,3.13,1.00,1.00,1.00,1.00,1.00,1.00,6.00,NaN
370,PFE,Pfizer,Health Care,Pharmaceuticals,101130000000.00,29750000000.00,263790000000.00,9.21,3.06,15.80,...,0.69,3.35,1.00,1.00,1.00,1.00,1.00,1.00,6.00,NaN
0,MMM,3M,Industrials,Industrial Conglomerates,35090000000.00,4150000000.00,68570000000.00,17.38,5.16,8.90,...,0.99,4.80,1.00,1.00,1.00,0.00,1.00,1.00,5.00,NaN
288,LMT,Lockheed Martin,Industrials,Aerospace & Defense,64170000000.00,4710000000.00,110510000000.00,24.22,9.73,9.10,...,0.66,2.68,1.00,1.00,1.00,1.00,1.00,1.00,6.00,NaN
342,NOC,Northrop Grumman,Industrials,Aerospace & Defense,34960000000.00,5670000000.00,74360000000.00,13.43,5.49,13.50,...,0.61,1.43,1.00,1.00,1.00,1.00,1.00,1.00,6.00,NaN
460,UNP,Union Pacific Corporation,Industrials,Railroads,23430000000.00,6850000000.00,145260000000.00,21.81,11.52,10.80,...,1.13,2.22,1.00,1.00,1.00,1.00,1.00,1.00,6.00,NaN
462,UPS,United Parcel Service,Industrials,Air Freight & Logistics,100100000000.00,10930000000.00,171640000000.00,16.06,10.74,15.90,...,1.07,3.04,1.00,1.00,1.00,1.00,1.00,1.00,6.00,NaN

In [6]:
controller.get_universe_df()

한국 시장의 유니버스 데이터 프레임을 저장합니다.

In [7]:
controller.get_universe_df()

===입력 가능 섹터 리스트===
['Industrials', 'Health Care', 'Information Technology', 'Communication Services', 'Consumer Staples', 'Consumer Discretionary', 'Utilities', 'Financials', 'Materials', 'Real Estate', 'Energy']
존재하지 않는 섹터입니다.
미국 시장의 유니버스 데이터 프레임을 저장합니다.

### get_initial_portfolio_df

In [5]:
controller.get_initial_portfolio_df()

한국 시장의 최초 포트폴리오 데이터 프레임을 조회합니다.

,CMP_KOR,SEC_NM_KOR,BPS,PER,PBR,EPS,DIV,DPS,매출액,영업이익,당기순이익,ROA,ROE,베타,MKT_VAL,Score
종목코드,,,,,,,,,,,,,,,,
005830,DB손해보험,금융,110605.00,3.83,0.50,14482.00,6.31,3500.00,59734.00,3908.00,2983.00,1.80,19.10,0.55,2593404.00,13.00
055550,신한지주,금융,88548.00,4.78,0.39,7308.00,5.62,1960.00,75869.00,17492.00,13399.00,0.80,11.50,0.73,14679149.00,12.00
105560,KB금융,금융,121808.00,4.18,0.38,11134.00,6.32,2940.00,257208.00,16002.00,13080.00,0.80,11.70,0.74,14640560.00,12.00
137310,에스디바이오센서,건강관리,21658.00,2.51,1.27,10918.00,4.61,1266.00,7950.00,3481.00,3386.00,48.60,63.70,0.13,992180.00,14.00
145720,덴티움,건강관리,33841.00,13.55,2.58,6434.00,0.29,250.00,967.00,352.00,362.00,17.30,32.50,0.88,530861.00,13.00
096530,씨젠,건강관리,20971.00,2.65,1.31,10359.00,3.65,1000.00,1284.00,130.00,251.00,25.50,33.50,1.16,944455.00,13.00

### get_portfolio_ohlcv

In [6]:
ohlcv = controller.get_portfolio_ohlcv(ratio=False)
ohlcv

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

,005830,055550,105560,001450,016360,ABT,MRK,PFE
Open,54800,35450,45550,30600,31350,103.18,92.27,42.89
High,57400,36250,47100,31400,31950,103.92,93.36,43.38
Low,53800,35400,45550,30400,31300,100.79,91.74,42.36
Close,56800,35700,46750,31150,31700,100.91,92.18,42.86
Volume,156329,1157733,1258433,274285,223412,6087200.00,9847600.00,16980500.00

In [5]:
ohlcv = controller.get_portfolio_ohlcv(ratio=True)
ohlcv

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

        005830   055550   105560   001450  016360      ABT      MRK      PFE
Open   0.01859  0.01868  0.01902  0.02000 0.00481  0.05361  0.03095  0.02706
High   0.03986  0.02113  0.03289  0.02782 0.00789  0.00815  0.00690  0.00510
Low    0.00186  0.01871  0.02360  0.02703 0.00968  0.03184  0.02767  0.01583
Close  0.04029  0.02292  0.04586  0.02805 0.02258 -0.01522 -0.00335 -0.00279
Volume 0.02531 -0.20617 -0.09287 -0.25406 0.01255 -0.02619  0.04954 -0.26603

### get_rebalanced

In [6]:
rebalanced_portfolio = controller.get_rebalanced()
rebalanced_portfolio

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

[0.06686101,
 0.11355152,
 0.11447301,
 0.1145426,
 0.10967606,
 0.10794546,
 0.11660503,
 0.10678197,
 0.14956334]

In [13]:
from Dinger import info

info.now_portfolio

[0.06686101,
 0.11355152,
 0.11447301,
 0.1145426,
 0.10967606,
 0.10794546,
 0.11660503,
 0.10678197,
 0.14956334]